Shopwisely/Shopwisely/urls.py
from django.urls import path,include

urlpatterns = [
    path('products/', include('products.urls')),
    path('admins/', include('admins.urls')),
    path('' , include('accounts.urls'))
]

Shopwisely/admins/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('dashboard', views.dashboard),
    path('updatestatus/<int:order_id>', views.update_status),



]

Shopwisely/products/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('homepage' ,views.homepage),
    path('category_form',views.category_form),
    path('get_category',views.get_category),
    path('delete_category/<int:category_id>', views.delete_category),
    path('update_category/<int:category_id>', views.category_update_form),


    path('product_form',views.product_form),
    path('get_product',views.get_product),
    path('delete_product/<int:product_id>', views.delete_product),
    path('update_product/<int:product_id>', views.product_update_form),

    path('get_category_user',views.show_categories),
    path('get_product_user', views.show_products),
    path('add_to_cart/<int:product_id>', views.add_to_cart),
    path('mycart',views.show_cart_items),
    path('remove_cart_item/<int:cart_id>', views.remove_cart_item),
    path('order_form/<int:product_id>/<int:cart_id>',views.order_form),
    path('my_order', views.my_order),
    path('menu/<int:cat_id>', views.category_button),



]

Shopwisely/products/models.py
from django.db import models
from django.core.validators import *
from django.core import validators
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=200,null=True,validators=[validators.MinLengthValidator(2)])
    category_descripation = models.TextField(null=True)
    category_image = models.ImageField(upload_to='static/uplods',null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.category_name

class Products(models.Model):
    product_name = models.CharField(max_length=200)
    product_price = models.FloatField()
    product_image = models.ImageField(upload_to='static/uplods')
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return self.product_name


class Cart(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Delivered', 'Delivered'),
    )
    PAYMENT = (
        ('Cash On Delivery', 'Cash On Delivery'),
        ('Esewa', 'Esewa'),
        ('Khalti', 'Khalti'),
    )
    product = models.ForeignKey(Products, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    quantity = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(20)])
    total_price = models.IntegerField(null=True)
    status = models.CharField(max_length=200, choices=STATUS, default='Pending')
    payment_method = models.CharField(max_length=200, choices=PAYMENT, null=True)
    payment_status = models.BooleanField(default=False, null=True, blank=True)
    contact_no = models.CharField(validators=[MinLengthValidator(9), MaxLengthValidator(10)], null=True, max_length=10)
    contact_address = models.CharField(max_length=200, null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)

Shopwisely/products/forms.py
from django import forms
from django.forms import ModelForm
from .models import Category,Products,Order


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class ProductForm(ModelForm):
    class Meta:
        model = Products
        fields = "__all__"

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['quantity', 'contact_no', 'contact_address','payment_method']

Shopwisely/products/views.py
from django.shortcuts import render,redirect
from .forms import CategoryForm,ProductForm,OrderForm
from django.contrib import messages
from .models import Category,Products,Cart,Order
from accounts.auth import admin_only,user_only
from django.contrib.auth.decorators import login_required
from .filters import ProductFilter
import os

# Create your views here.
@user_only
def homepage(request):
    context={
        'activate_home': 'active'
    }
    return render(request,'products/homepage.html',context)




@login_required
@admin_only
def category_form(request):
    if request.method == "POST":
        form = CategoryForm(request.POST , request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,'Category added sucesfully')
            return redirect("/products/get_category")
        else:
            messages.add_message(request,messages.ERROR,'Unable to add category')
            return render(request,'products/category_form.html',{'form_category':form})

    context ={
        'form_category': CategoryForm,
        'activate_category':'active'
    }
    return render(request,'products/category_form.html',context)

@login_required
@admin_only
def get_category(request):
    categories = Category.objects.all().order_by('-id')

    context ={
        'categories':categories,
        'activate_category':'active'
    }
    return render(request,'products/get_category.html',context)

@login_required
@admin_only
def delete_category(request,category_id):
    category = Category.objects.get(id=category_id)
    os.remove(category.category_image.path)
    category.delete()
    messages.add_message(request,messages.SUCCESS,'Category Deleted Sucessfully')
    return redirect("/products/get_category")

@login_required
@admin_only
def category_update_form(request, category_id):
    category = Category.objects.get(id=category_id)
    if request.method == "POST":
        if request.FILES.get('category_image'):
            os.remove(category.category_image.path)
        form = CategoryForm(request.POST,request.FILES,instance=category)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Category updated successfully')
            return redirect("/products/get_category")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to update category')
            return render(request, 'products/category_update_form.html', {'form_category':form})
    context ={
        'form_category': CategoryForm(instance=category),
        'activate_category': 'active'
    }
    return render(request, 'products/category_update_form.html', context)


@login_required
@admin_only
def product_form(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Food added successfully')
            return redirect("/products/get_product")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to add food')
            return render(request, 'products/product_form.html', {'form_food':form})
    context ={
        'form_product': ProductForm,
        'activate_product': 'active'
    }
    return render(request, 'products/product_form.html', context)


@login_required
@admin_only
def get_product(request):
    products = Products.objects.all().order_by('-id')
    product_filter =ProductFilter(request.GET,queryset=products)
    product_final = product_filter.qs
    context ={
        'products': product_final,
        'product_filter':product_filter,
        'activate_products':'active'
    }
    return render(request,'products/get_product.html',context)

@login_required
@admin_only
def delete_product(request, product_id):
    product = Products.objects.get(id=product_id)
    os.remove(product.product_image.path)
    product.delete()
    messages.add_message(request, messages.SUCCESS, 'Food Deleted Successfully')
    return redirect('/products/get_product')


@login_required
@admin_only
def product_update_form(request, product_id):
    product = Products.objects.get(id=product_id)
    if request.method == "POST":
        if request.FILES.get('product_image'):
            os.remove(product.product_image.path)
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Food updated successfully')
            return redirect("/products/get_product")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to update food')
            return render(request, 'products/product_form.html', {'form_food':form})
    context ={
        'form_product': ProductForm(instance=product),
        'activate_product': 'active'
    }
    return render(request, 'products/product_update_form.html', context)

@user_only
def show_products(request):
    products = Products.objects.all().order_by('-id')
    Product_filter = ProductFilter(request.GET,queryset=products)
    product_final = Product_filter.qs
    context = {
        'products':product_final,
        'product_filter':Product_filter,
        'activate_products_user': 'active'
    }
    return render(request, 'products/show_product.html', context)

def show_categories(request):
    categories  = Category.objects.all().order_by('-id')
    context = {
        'categories':categories,
        # 'cart_no': cart_count,
        'activate_category_user':'active'
    }
    return render(request, 'products/show_categories.html', context)

@login_required
@user_only

def add_to_cart(request,product_id):
    user =  request.user
    product = Products.objects.get(id=product_id)
    cart = Cart.objects.create(product=product , user=user)
    if cart:
        messages.add_message(request, messages.SUCCESS,"Item added to cart")
        return redirect('/products/mycart')
    else:
        messages.add_message(request, messages.ERROR,"Ubale to add items to cart")


@login_required
@user_only
def remove_cart_item(request, cart_id):
    item = Cart.objects.get(id=cart_id)
    item.delete()
    messages.add_message(request,messages.SUCCESS,"Cart item removed Sucesfully")
    return redirect('/products/mycart')

@login_required
@user_only
def show_cart_items(request):
    user = request.user
    items = Cart.objects.filter(user=user)
    cart_items = Cart.objects.filter(user=request.user)
    cart_count = cart_items.count()
    context ={
        'items':items,
        'activate_my_cart':'active',
        'cart_no': cart_count
    }

    return render(request,'products/mycart.html',context)


@login_required
@user_only
def order_form(request,product_id,cart_id):
    user = request.user
    product =Products.objects.get(id=product_id)
    cart_item= Cart.objects.get(id = cart_id)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            quantity = request.POST.get('quantity')
            price = product.product_price
            total_price = int(quantity)*int (price)
            contact_no = request.POST.get('contact_no')
            contact_address = request.POST.get('contact_address')
            payment_method = request.POST.get('payment_method')
            order = Order.objects.create(
                product=product,
                user = user,
                quantity =quantity,
                total_price= total_price,
                contact_no = contact_no,
                contact_address = contact_address,
                status = "Pending",
                payment_method=payment_method,
                payment_status=False
            )

            if order:
                messages.add_message(request,messages.SUCCESS,"Item Orders")
                cart_item.delete()
                context = {
                    'order': order,
                    'cart': cart_item
                }
                return render(request, "products/esewa_payment.html", context)
        else:
            messages.add_message(request, messages.ERROR, "Something went wrong")
            return render(request, 'products/order_form.html', {'order_form': form})

    context = {
        'order_form':OrderForm,
        'activate_my_orders':'active'
    }
    return render(request, 'products/order_form.html', context)


@login_required
@user_only
def my_order(request):
    user = request.user
    items = Order.objects.filter(user=user).order_by('-id')
    cart_items = Cart.objects.filter(user=request.user)
    cart_count = cart_items.count()
    context = {
        'items':items,
        'cart_no': cart_count,
        'activate_myorders':'active'
    }
    return render(request, 'products/my_order.html', context)

@user_only
def category_button(request, cat_id):
    categories =Category.objects.filter(id=cat_id).order_by('-id')
    context = {
        'categories':categories,
        'activate_menu':'active'
    }
    return render(request, 'products/category_button.html', context)


# import requests as req
def esewa_verify(request):
    import xml.etree.ElementTree as ET
    o_id = request.GET.get('oid')
    amount = request.GET.get('amt')
    refId = request.GET.get('refId')
    url = "https://uat.esewa.com.np/epay/transrec"
    d = {
        'amt': amount,
        'scd': 'EPAYTEST',
        'rid': refId,
        'pid': o_id,
    }
    resp = request.post(url, d)
    root = ET.fromstring(resp.content)
    status = root[0].text.strip()
    if status == 'Success':
        order_id = o_id.split("_")[0]
        order = Order.objects.get(id=order_id)
        order.payment_status = True
        order.save()
        cart_id = o_id.split("_")[1]
        cart = Cart.objects.get(id=cart_id)
        cart.delete()
        messages.add_message(request, messages.SUCCESS, 'Payment Successful')
        return redirect('/products/my_order')

Shopwisely/products/templates/products/category_button.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title> Details Category</title>
{% endblock title %}

{% block main_content%}
<h1> Categories wise items</h1>
<div class="container">
    <div class="row justify-content-around">
        {% for i in categories%}
        {% for j in i.products_set.all %}
        <div class="card col-md-2 m-1">
            <img src="/{{j.product_image}}" class="card-img-top" alt="...">
            <div class="card-body p-2">
                <h5 class="card-title">{{j.product_name}}</h5>
                <p class="card-text">{{j.product_category}}</p>
                <a href="/products/menu" class="btn btn-primary">Details</a>
            </div>
        </div>

        {% endfor %}
        {% endfor %}
    </div>
</div>
{% endblock main_content %}

Shopwisely/products/templates/products/category_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Add Category</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Add New Category</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_category | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter category name"
    form_fields[2].placeholder = "Enter category description"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}
© 2021 GitHub, Inc.

Shopwisely/products/templates/products/category_update_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Update Category</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Update Category</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_category | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[2].placeholder = "Enter category name"
    form_fields[3].placeholder = "Enter category description"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}
© 2021 GitHub, Inc.

Shopwisely/products/templates/products/esewa_payment.html
{% load bootstrap %}
{% block title %}
<title>Add Food</title>
{% endblock%}
{% block main_content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1 class="text-center">You are being redirected to Esewa. Please wait.....</h1>
            <div class="card py-2 px-2" style="display:none;">
                <form action="https://uat.esewa.com.np/epay/main" method="POST" id="esewa_form">
                    <input value="{{order.total_price}}" name="tAmt" type="text" readonly>
                    <input value="{{order.total_price}}" name="amt" type="text" readonly>
                    <input value="0" name="txAmt" type="hidden" readonly>
                    <input value="0" name="psc" type="hidden" readonly>
                    <input value="0" name="pdc" type="hidden" readonly>
                    <input value="EPAYTEST" name="scd" type="hidden">
                    <input value="{{order.id}}_{{cart.id}}" name="pid" type="hidden">
                    <input value="http://127.0.0.1:8000/products/my_order" type="hidden" name="su">
                    <input value="{{request.build_absolute_uri}}" type="hidden" name="fu">
                    <input value="Submit" type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    setTimeout(function(){
    document.getElementById('esewa_form').submit()
    }, 1000)
</script>
{% endblock main_content %}

Shopwisely/products/templates/products/get_category.html
{% extends 'layout-admin.html' %}
{% block title %}
<title>All Categories</title>
{% endblock%}

{% block main_content %}
<div class="container">
    <div class="row">

        <div class="col-md-10 offset-md-1">
            <h1 class="text-center">All Categories</h1>
            {% include 'messages.html' %}
            <div class="card py-2 px-2">
                <a class="btn btn-primary btn-sm ms-auto"
                href="/products/category_form"
                >Add New Category</a>
                <table class="table-striped">
                    <tr>
                        <th>Category Name</th>
                        <th>Description</th>
                        <th>Category Image</th>
                        <th>Date</th>
                        <th>Actions</th>

                    </tr>
                    {% for i in categories %}
                    <tr>
                        <td> {{ i.category_name }}</td>
                        <td> {{ i.category_descripation}}</td>
                        <td><img src="/{{i.category_image}}" width="200"> </td>
                        <td> {{ i.created_date }}</td>
                        <td><a class="btn btn-primary btn-sm" href="/products/update_category/{{i.id}}">Edit</a> &nbsp;
                            <a class="btn btn-danger btn-sm"
                               href="/products/delete_category/{{i.id}}"
                               onclick="return confirm('Are you sure want to delete this category?')" >Delete</a></td>

                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Shopwisely/products/templates/products/get_product.html
{% extends 'layout-admin.html' %}
{% block title %}
<title>All Products</title>
{% endblock%}

{% block main_content %}
<div class="container">
    <div class="row">

        <div class="col-md-10 offset-md-1">
            <h1 class="text-center">All Products</h1>
            {% include 'messages.html' %}
            <div class="card py-2 px-2">
                <a class="btn btn-primary btn-sm ms-auto"
                href="/products/product_form"
                >Add New Product</a>
                <div class="card card-body">
                    <form class="form" method="get">
                        {{product_filter.form}}
                        <button class="btn btn-outline-info" type="submit">Search</button>
                    </form>
                </div>
                <table class="table-striped">
                    <tr>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Category</th>
                        <th>Image</th>

                        <th>Actions</th>
                    </tr>
                    {% for i in products %}
                    <tr>
                        <td> {{ i.product_name }}</td>
                        <td> {{ i.product_price }}</td>
                        <td> {{ i.category.category_name }}</td>
                        <td><img src="/{{i.product_image}}" width="200"> </td>
                        <td><a class="btn btn-primary btn-sm" href="/products/update_product/{{i.id}}">Edit</a> &nbsp;
                            <a class="btn btn-danger btn-sm"
                               href="/products/delete_product/{{i.id}}"
                               onclick="return confirm('Are you sure want to delete this food?')" >Delete</a></td>

                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Shopwisely/products/templates/products/my_order.html
{% extends 'layout.html' %}
{% block title %}
<title>MyOrders</title>
{% endblock title %}
{% block main_content %}

<div class="container-fluid" style="min-height:300px;">
    <div class="row">
        <div class="col mt-4 mb-4">
            <h1 class="text-center text-uppercase m-4 font-weight-bold">My Order History</h1>
            {% include 'messages.html' %}
            <div class="card shadow-lg ">
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Item Name</th>
                            <th>Item Price</th>
                            <th>Quantity</th>
                            <th>Total Price</th>
                            <th>Ordered Date</th>
                            <th>Contact No</th>
                            <th>Delivery Location</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody class="align-items-center">
                        {% for item in items %}
                        <tr >
                            <td>{{item.product.product_name}}</td>
                            <td>Rs.{{item.product.product_price}}</td>
                            <td>{{item.quantity}}</td>
                            <td>{{item.total_price}}</td>
                            <td>{{item.created_date}}</td>
                            <td>{{item.contact_no}}</td>
                            <td>{{item.contact_address}}</td>
                            <td>{{item.status}}</td>
                                                    </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>

    </div>
</div>
</div>
{% endblock %}

Shopwisely/products/templates/products/mycart.html
{% extends 'layout.html' %}
{% block title %}
<title>My Cart</title>
{% endblock%}

{% block main_content %}
<div class="container">
    <div class="row">

        <div class="col-md-10 offset-md-1">
            <h1 class="text-center">My Cart</h1>
            {% include 'messages.html' %}
            <div class="card py-2 px-2">
                <table class="table-striped">
                    <tr>
                        <th>Product Name</th>
                        <th>Product Price</th>
                        <th>Date Added</th>
                        <th>Actions</th>
                    </tr>
                    {% for i in items %}
                    <tr>
                        <td> {{ i.product.product_name}}</td>
                        <td> {{ i.product.product_price }}</td>
                         <td> {{ i.created_date }}</td>
                        <td><a class="btn btn-primary btn-sm" href="/products/remove_cart_item/{{i.id}}">Removed</a> &nbsp;
                            <a class="btn btn-danger btn-sm"
                               href="/products/order_form/{{i.product.id}}/{{i.id}}"
                               onclick="return confirm('Are you sure want tadd this category?')" >Order</a></td>

                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Shopwisely/products/templates/products/order_form.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block title %}
    <title>Order Item</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Order Items</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ order_form | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Proceed to Payment</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[2].placeholder = "Enter Quantity"
    form_fields[3].placeholder = "Enter Contact no"
    form_fields[4].placeholder = "Enter Address"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}
© 2021 GitHub, Inc.

Shopwisely/products/templates/products/product_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Add Product</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Add new Product</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_product | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
     form_fields[1].placeholder = "Enter Product Name"
    form_fields[2].placeholder = "Enter Product Price"



   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}
© 2021 GitHub, Inc.

Shopwisely/products/templates/products/product_update_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Update Products</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Update Products</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form myForm" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_product | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[2].placeholder = "Enter category name"
    form_fields[3].placeholder = "Enter category description"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}
© 2021 GitHub, Inc.

Shopwisely/products/templates/products/show_categories.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Category</title>
{% endblock title %}

{% block main_content%}
<h1>All Categories</h1>
<div class="container">
    <div class="row justify-content-around">
        {% for i in categories%}
        <div class="card col-md-2 m-1">
            <img src="/{{i.category_image}}" class="card-img-top" alt="...">
            <div class="card-body p-2">
                <h5 class="card-title">{{i.category_name}}</h5>
                <p class="card-text">{{i.category_descripation}}</p>
                <a href="/products/menu/{{i.id}}" class="btn btn-primary">Details</a>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock main_content %}

Shopwisely/products/templates/products/show_product.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Category</title>
{% endblock title %}

{% block main_content%}
<div class="card card-body ">
                    <form class="form" method="get">
                        {{product_filter.form}}
                        <button class="btn btn-outline-info" type="submit">Search</button>
                    </form>
<h1>All Products</h1>
<div class="container ">
    <div class="row justify-content-around">
        {% for i in products %}
        <div class="card col-md-2 m-2">
           <img src="/{{i.product_image}}" class="card-img-top" alt="...">
            <div class="card-body p-2 ">
                <h5 class="card-title">{{i.product_name}}</h5>
                <p class="card-text">Rs.{{i.product_price}}</p>
                 <p class="card-text">{{i.category.category_name}}</p>
                <a href="/products/add_to_cart/{{i.id}}" class="btn btn-info" onclick=" return confirm('Are you sure want to add to cart)">Add to cart</a>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock main_content %}